#!/usr/bin/env bash
set -eo pipefail

if [ -e .commit ]
then
    rm .commit
    echo "Building output"
    {
      npm run build-once &&
      git add dist/* &&
      git commit --amend -C HEAD --no-verify
    } || {
      echo "Building failed, uncommitting"
      git reset HEAD~1
    }
fi
