#!/usr/bin/env bash
set -eo pipefail

if [ -e .commit ]
then
    rm .commit
    echo "Building output"
    {
      git stash -u &&
      npm run build &&
      git add dist/* &&
      git commit --amend -C HEAD --no-verify
    } || {
      echo "Building failed, uncommitting"
      git reset HEAD~1
    }
    git stash pop
fi
